language: node_js

node_js:
  - "stable"

services:
  - mongodb
  - redis-server

before_script:
  - yarn add global gulp

script:
  - gulp lint
  - gulp test

cache:
  yarn: true
  directories:
    - node_modules
